#!/bin/bash

repolistfile="$HOME/.repolist"

if [ -f "$repolistfile" ]; then
  echo "Repofile found"
else
  echo "Please create a $repolistfile"
  exit
fi

for dir in $(cat $repolistfile | sort | uniq); do
  echo '------------------------------------------------------------------'
  echo $dir
  echo '------------------------------------------------------------------'
  if [ -d $dir ]; then
    cd $dir
    if [ -d .git ]; then
      git fetch
      git gc
    elif [ -d .svn ]; then
      svn up .
    fi
  else
    echo "Directory:$dir does not exists....."
  fi
  echo ' '
done
